### ISSUE TITLE
support Manter dynamic properties describing host attributes

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/unl-nsm#4]
Some Manter lab specimen are explicitly linked to their host records (e.g., https://arctos.database.museum/guid/HWML:Para:65988 parasite of https://arctos.database.museum/guid/MSB:Mamm:70448 ) .

Others, like http://arctos.database.museum/guid/HWML:Para:49529 appear to contain host information in their dynamic properties (e.g., https://www.gbif.org/occurrence/3125910298, ```age class=adult;location in host=gallbladder;verbatim host ID=Ictalurus punctatus ``` and attached screenshot)

Suggest to add support for GloBI to better understand the dynamic properties in the Manter dataset. 

A first challenge will be to make a list of all used dynamic properties and translate these into terms that GloBI understands. 

fyi @seltmann  @gracz-UNL @campmlc 
 
related to https://github.com/ArctosDB/arctos/issues/3176#issuecomment-853971972 .

![Screenshot from 2021-06-03 11-11-20](https://user-images.githubusercontent.com/1084872/120692662-ed2b3800-c45c-11eb-955f-1ec9c324f856.png)

**Comment by jhpoelen** [comment]
At first glance, these are the dynamic properties used in the Manter data along with their frequency of occurrence:

```
$ unzip -p datasets/local/a92cc9b3a74b289b6881d58dbf8f4be447684885b779f1bd1eb31a8267940bf0 occurrence.txt | cut -f14 | tr ';' '\n' | sed 's/=.*//g' | sort | uniq -c | sort -nr
  58760 verbatim host ID
  52841 location in host
  18393 sex
  13939 age class
   5637 verbatim collector
   4761 verbatim host sex
   2518 verbatim host age
```

**Comment by jhpoelen** [comment]
I've added a first pass at translating Manter dynamic properties to GloBI terms:

```
        putIfAbsentAndNotBlank(properties, TARGET_TAXON_NAME, properties.get("verbatim host ID"));
        putIfAbsentAndNotBlank(properties, TARGET_BODY_PART_NAME, properties.get("location in host"));
        putIfAbsentAndNotBlank(properties, TARGET_SEX_NAME, properties.get("verbatim host sex"));
        putIfAbsentAndNotBlank(properties, TARGET_LIFE_STAGE_NAME, properties.get("verbatim host age"));

        putIfAbsentAndNotBlank(properties, SOURCE_LIFE_STAGE_NAME, properties.get("age class"));
        putIfAbsentAndNotBlank(properties, SOURCE_SEX_NAME, properties.get("sex"));

        if (StringUtils.isNoneBlank(properties.get("verbatim host ID"))) {
            properties.put(INTERACTION_TYPE_NAME, InteractType.HAS_HOST.getLabel());
            properties.put(INTERACTION_TYPE_ID, InteractType.HAS_HOST.getIRI());
        }
```

where SOURCE_* is the parasite and TARGET_* is the host. 

Open to suggestion to improve this interpretation.

**Comment by seltmann** [comment]
@jhpoelen I see these properties as really important to support. Many of these came up in the TPT workshop as **additional properties** of host-parasite relationships as recorded in:

Kathryn Sullivan, Katja Seltmann, Jorrit Poelen, & Jennifer M. Zaspel. (2020, May). Making Parasite-Host Associations Visible in Terrestrial Parasite Tracker (TPT) (Version 0.0.1). Zenodo. http://doi.org/10.5281/zenodo.3941952

I see one challenge is the alignment of additional properties as one person may call the properties slightly different name/terms but could have the same meaning. For example, one data provider could use **host sex** and another could just use the term **sex**

**Comment by jhpoelen** [comment]
@seltmann yes, I can see how dataset specific mappings might be needed to take into account the variation of usage across datasets. Hoping to figure out these details as they come up in specific examples. 

Also, an initial support for dynamic property mapping for Manter resulted in about 60k indexed interactions, consisting of 859 interactions linked to MSB Mamm and 58763 indexed from dynamic properties. Great example of how translation of dynamic properties can yield a lot of great insights into interactions already recorded. 

See also attached file. Note that next release of elton will add support for this dynamic property translation.

[manter-interactions-2021-06-03.tsv.txt.gz](https://github.com/globalbioticinteractions/unl-nsm/files/6593747/manter-interactions-2021-06-03.tsv.txt.gz)

**Comment by jhpoelen** [comment]
A first version of the Harold W. Manter Laboratory of Parasitology including indexed interaction data from dynamic properties has been available via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Funl-nsm&interactionType=interactsWith . See attached screenshots. 

![Screenshot from 2021-06-18 09-14-28](https://user-images.githubusercontent.com/1084872/122589853-a0775d80-d015-11eb-8c5e-78e88402d45b.png)
![Screenshot from 2021-06-18 09-14-00](https://user-images.githubusercontent.com/1084872/122589864-a53c1180-d015-11eb-921d-3dc035c7062d.png)
![Screenshot from 2021-06-18 09-13-13](https://user-images.githubusercontent.com/1084872/122589866-a53c1180-d015-11eb-998d-fe890adfb2f6.png)
![Screenshot from 2021-06-18 09-09-35](https://user-images.githubusercontent.com/1084872/122589871-a705d500-d015-11eb-824c-805e44a8283b.png)

**Comment by jhpoelen** [comment]
Also note that Arctos picked up the newly indexed Manter Lab Parasite records via GloBI;s support for custom dynamic property notations even through no explicit links were made available in Arctos. See e.g., http://arctos.database.museum/guid/HWML:Para:49529 and attached screenshot. 

fyi @campmlc @dustymc @Jegelewicz 

![Screenshot from 2021-06-18 09-15-37](https://user-images.githubusercontent.com/1084872/122590066-e6ccbc80-d015-11eb-948e-af97f5ddd865.png)
